### ISSUE TITLE
License

### ISSUE THREAD

**Issue by doersino** [dotpack/php-boiler-pipe#2]
I'd like to use this library in one of my projects. Am I incorrect in assuming that I may use this code under the conditions of the Apache License 2.0, which is used for the [project](https://github.com/kohlschutter/boilerpipe) this code is based on?

Adding a `LICENSE` file might help resolve future questions of similar nature.

**Comment by dotpack** [comment]
@doersino thank you. You can use this code under the conditions of Apache License 2.0.

I'm not absolutely sure that I added license correctly. I need some time to figure this out.
